"""added addresses

Revision ID: 97a1ad4f5b24
Revises: 
Create Date: 2021-10-21 16:34:20.331155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97a1ad4f5b24'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_kinds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_kinds_id'), 'activity_kinds', ['id'], unique=False)
    op.create_table('addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_addresses_id'), 'addresses', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('renters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('e_mail', sa.String(), nullable=True),
    sa.Column('activity_kind_id', sa.Integer(), nullable=True),
    sa.Column('demanded_addr_id', sa.Integer(), nullable=True),
    sa.Column('meters_required', sa.Integer(), nullable=True),
    sa.Column('comments', sa.String(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['activity_kind_id'], ['activity_kinds.id'], ),
    sa.ForeignKeyConstraint(['demanded_addr_id'], ['addresses.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_renters_comments'), 'renters', ['comments'], unique=False)
    op.create_index(op.f('ix_renters_id'), 'renters', ['id'], unique=False)
    op.create_index(op.f('ix_renters_name'), 'renters', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_renters_name'), table_name='renters')
    op.drop_index(op.f('ix_renters_id'), table_name='renters')
    op.drop_index(op.f('ix_renters_comments'), table_name='renters')
    op.drop_table('renters')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_addresses_id'), table_name='addresses')
    op.drop_table('addresses')
    op.drop_index(op.f('ix_activity_kinds_id'), table_name='activity_kinds')
    op.drop_table('activity_kinds')
    # ### end Alembic commands ###
